# Generated by Django 4.1.7 on 2023-02-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Date',
            field=models.DateField(default='1998-12-24'),
            preserve_default=False,
        ),
    ]
